### PR TITLE
Buttons grid

### PR DESCRIPTION
**Pull request by jeremybarbet**
Two buttons to toggle each type of grid. Sometimes it's really annoying to have both enable at same times.

### CODE REVIEW

**Comment by birkir** [comment]
This is cool.

One thing, can we use icons or any shorter text for the buttons? We're trying to keep the devtools as compact as we can, so they aren't in the way.

**Comment by jeremybarbet** [comment]
Yeah I was thinking about that, it's way too long. What about two icons like this?
screen shot 2017-03-16 at 15 25 31

**Comment by birkir** [comment]
This looks great!

**Comment by jeremybarbet** [comment]
Done!

**Comment by jeremybarbet** [comment]
Ok give me one seconde, I once again missed vertical and horizontal order...

**Comment by jeremybarbet** [comment]
Ok I fixed it!

**Pull request merged**
