### PR TITLE
Adds analytics

### PR DESCRIPTION
**Pull request by baldurh**
- Google Analytics via react-ga
- Facebook Pixel
- Twitter Pixel

I’m not expecting this to be merged in. I just wanted to create a PR so that someone can review it.
I suggest we then keep this as a branch which can then be merged with master in new projects if needed.

### CODE REVIEW

**Comment by birkir** [comment]
Looking good. Maybe use location.href for URL's to include query strings and hash? Just a thought, don't know if it serves any purpose.

**Comment by baldurh** [comment]
I think you would not want to track pages differently depending on the query string, but I don’t know.

**Comment by birkir** [comment]
Allright, sounds fair, people can tweak that if they want.

**Comment by baldurh** [comment]
I think the idea was to keep this as a seperate branch for people to merge into new projects if they need Analytics 🙈

**Comment by birkir** [comment]
Whoops, i can rollback. But feature branches are very hard to maintain, we stopped doing those in react-universally

**Comment by baldurh** [comment]
What do you think @finnursig, @osk?

**Comment by osk** [comment]
I think it's fine to keep this on master

**Comment by baldurh** [comment]
Cool. Let’s do that ❤️

**Pull request merged**
