### PR TITLE
CSS setup tidy

### PR DESCRIPTION
**Pull request by organdonor47**
tidying some of the base css setup

### CODE REVIEW

**Comment by organdonor47** [comment]
@birkir @mdmagnusson @osk care to take a look at this and let me know your thoughts? have added & removed a few bits & pieces for base css, and also made a couple changes to segment.

**Comment by birkir** [comment]
Looks real good so far, still a WIP?

**Comment by organdonor47** [comment]
@birkir not anymore, sorry! edited

**Comment by birkir** [comment]
Thank you - much needed!

**Comment by osk** [comment]
Why do we want `user-scalable=no` by default?

**Comment by birkir** [comment]
@osk Guess because of the comment right next to it 😄 
`// prevents inputs from zooming, but iOS still allows normal pinch zoom`

**Comment by osk** [comment]
I didn't know that it had stopped disabling pinch zoom on mobile in general, at least for newer browsers. And can't find any info on it, just iOS 10, but tested on my device and that works and I trust @organdonor47 😊

**Pull request merged**
