### PR TITLE
Remove useless svg-loader

### PR DESCRIPTION
**Pull request by jeremybarbet**
I was probably blind at the time I did this but the `file-loader` is also working for svg images on scss file, so let's just remove the extra stuff I did, to make it simpler.

e.g.
```css
.logo {
  background-image: url('!file-loader!assets/images/ueno-logo.svg');
}
```

### CODE REVIEW

**Comment by birkir** [comment]
Cool! Thanks.

I thought about having
 - `.svgx` for SVG > React.Component
 - `./assets/**/*.svg` as file-loader and all other files SVG > React.Component (like `./components/Logo/Logo.svg`)

**Comment by jeremybarbet** [comment]
I've seen that you introduced it on CRA. What's the difference with the way we import SVG at the moment? Does it mean we will get ride of the `!file-loader!` thing on `.js` and `.scss` files?

**Comment by birkir** [comment]
I'm not sure yet. I don't want to risk making a transition from old project to cra harder.

But yes that was the idea, not having to set loaders by query strings in require, because as you know the loaders are heavily configured and you could be skipping a loader we always put on files to optimize them or a configuration specially set for production etc.

**Comment by jeremybarbet** [comment]
Alright, I see. I think we could tackle this on the separate PR, if we want to introduce on the starter kit too, right?

**Comment by chrisberks** [comment]
Could a new `Rule`, using the `issuer` property, be used to solve this?

`internal/webpack/configFactory.js`.
```
// SVG IMPORT loader from within css and scss files
{
  test: /\.svg$/,
  issuer: /(\.scss|\.css)$/,
  loader: 'svg-url-loader',
  query: {
    ...
  },
},

// SVG IMPORT loader
{
  test: /\.svg$/,
  use: [
    'babel-loader',
    'svg-to-jsx-loader',
  ],
},
```

This way all SVG files in SCSS/CSS files are handled separately. The idea is that you only ever inline SVG unless it's some repeated icon, then possibly use DataUrls in CSS (`svg-url-loader` uses `file-loader` as fallback). Here's my limited research:

Why inline SVG
https://www.youtube.com/watch?v=af4ZQJ14yu8
https://manu.ninja/inline-svg-how-i-learned-to-stop-worrying-and-love-gzip/

Why DataUrls
https://codepen.io/tigt/post/optimizing-svgs-in-data-uris

**Pull request merged**
