### PR TITLE
More naive static build based on existing build scripts

### PR DESCRIPTION
**Pull request by uooq**
Trivializing the static build further... before I was doing some fancy stuff to launch the SSR-based server before making calls to save off the HTML, now you just do the "normal" build first and use that as a starting place. 

The "crawling" part is still totally trivial... make requests and save the pages-- the main point is that this is easily wired up to be a heroku-executed build step... simply replacing the npm build & start scripts means we can use the normal heroku pipeline stuff and run/deploy working static builds.

### CODE REVIEW

**Comment by uooq** [comment]
Trivializing the static build further... before I was doing some fancy stuff to launch the SSR-based server before making calls to save off the HTML, now you just do the "normal" build first and use that as a starting place. 

The "crawling" part is still totally trivial... make requests and save the pages.

**Review by finnursig — COMMENTED** [review]
Currently the build is outputting references to the dev server and thus not working.

I used `yarn build:static`

**Comment by uooq** [comment]
I don't understand what your comment means @finnursig.  What references are being output where?

Per the updated readme, you need to do a normal build before the static build, so you should run `yarn build && yarn build:static`

**Comment by finnursig** [comment]
After using `yarn build` it works :+1:

**Pull request merged**
