### PR TITLE
Use useStaticRendering to fix forceUpdate errors

### PR DESCRIPTION
**Pull request by jeremybarbet**

### CODE REVIEW

**Comment by birkir** [comment]
Is this only happening on the server?

**Comment by jeremybarbet** [comment]
It happens on client side too. Basically, when we create a container with a store within it, we get the forceUpdate issue when we read values from the store. With this, we don't get it it anymore.

**Comment by birkir** [comment]
You shouldn't use static renderer on the client, all dynamic updates will stop working, or am I wrong?

**Comment by jeremybarbet** [comment]
What do you mean by "dynamic updates"?

We use it on a lot of projects (ueno.co, nova), and I haven't notice any issue with it, but I might be wrong too.

cc/ @geirlandro

**Comment by birkir** [comment]
From the mobx docs.

> Server Side Rendering with useStaticRendering
> When using server side rendering, normal lifecycle hooks of React components are not fired, as the components are rendered only once. Since components are never unmounted, observer components would in this case leak memory when being rendered server side. To avoid leaking memory, call useStaticRendering(true) when using server side rendering. This makes sure the component won't try to react to any future data changes.

**Comment by jeremybarbet** [comment]
Yeah I read that.

Well, what do you recommend to fix this forceUpdate warnings then? We were doing bunch of reactions before, but it was really a mess

screen shot 2018-05-07 at 10 10 47

**Comment by birkir** [comment]
This is caused by react tree walker which triggers mount twice. I think we can fix it with the new react-async-bootstrapper api, it is harmless but annoying.

**Pull request closed without merging**
